name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to production
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_nyKxqomq9Rg2wEbXQbVQoRQJ
          VERCEL_PROJECT_ID: prj_cu3b1yHlquIJQYhDDySssZ6eZlHp
